### ISSUE TITLE
dap is not working with any languages than Java

### ISSUE THREAD

**Issue by bmihovski** [imbacraft/dusk.nvim#11]
When trying to debug any other languages than java the dap doesn't work and failing with error

```
The selected configuration references adapter `codelldb`, but dap.adapters.codelldb is undefined
```
Here a potential fix/workaround. With the plugin below the DAP started working again
```lua
	{
		"jay-babu/mason-nvim-dap.nvim",
		event = "VeryLazy",
		dependencies = {
			"williamboman/mason.nvim",
			"mfussenegger/nvim-dap",
		},
		opts = {
			handlers = {},
		},
	},
```

**Comment by imbacraft** [comment]
Good observation. Unfortunately this is for now intended. In the past I had used [dap-buddy](https://github.com/pocco81/dap-buddy.nvim) to configure DAPs for languages other than Java, but I did not include it in the main branch because I have not tested it enough. I intend to test it with Typescript. However, feel free to test it with other languages, or, even better, try to see if we have some other alternative for configuring DAP for other languages.

**Comment by bmihovski** [comment]
Thanks for the suggestion. As far I understood from mason-nvim-dap.nvim plugin docs this only an integration plugin mason and currently we are missing only that part. The rest of dap integration is working out of the box as it is now.

```
mason-nvim-dap bridges mason.nvim with the nvim-dap plugin - making it easier to use both plugins together.
```
https://github.com/jay-babu/mason-nvim-dap.nvim

**Comment by imbacraft** [comment]
@bmihovski Thanks for the suggestion also. I used it to setup DAP for Angular development (clientside + server side TS) but you can follow the example to set it up for Python and/or CPP. If you're lucky, the default setup will work. For TS it didn't. Check the latest commit on development branch.

**Comment by bmihovski** [comment]
This issue is solved now and the default config is working fine with Python and C++

**Comment by imbacraft** [comment]
Glad to hear the default is working fine!
